import Head from 'next/head';

import Header from 'components/Header';
import Footer from 'components/Footer';
import Hero from 'components/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <link rel='icon' type='image/png' href='/favicon-32x32.png' />
      </Head>

      <Header />
      <main>
        <Hero>Yo</Hero>
      </main>
      <Footer />
    </>
  );
}
